"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['flushi.py']
DATA_FILES = []
OPTIONS = {'packages': ['PySide2'],
           'iconfile': 'icon3.icns',
            'packages': ['certifi', 'py2app'], # you need to add cffi
        'plist': {
        'CFBundleDevelopmentRegion': 'English',
        'CFBundleIdentifier': "com.hackmike.flushi",
        'CFBundleVersion': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2020, Michele Berardi, All Rights Reserved"
    }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
